# Generated by Django 5.1.3 on 2024-12-02 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=60)),
                ('number_levels', models.IntegerField()),
                ('weighted_ratings', models.DecimalField(decimal_places=2, max_digits=3)),
                ('additional_inputs', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_pass', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=60)),
                ('user_display', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('guide_level', models.IntegerField()),
                ('guide_text', models.CharField(max_length=10000)),
                ('number_of_moves', models.IntegerField()),
                ('colors_required', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.user')),
            ],
        ),
    ]
