# Generated by Django 5.1.3 on 2025-04-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_seed_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='guide',
            name='title',
            field=models.CharField(default='Untitled Guide', max_length=100),
        ),
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(default='none alt-text', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
